# -*- coding: utf-8 -*-
"""
Created on Mon Dec 21 17:46:22 2020

@author: taita
"""


from collections import defaultdict

aut= defaultdict(list)                          #ディクショナリ（著者）
aut["柴田淳"].append("みんなのpython")
aut["柴"].append("みんなのpython")
aut["柴田"].append("みんなのpython")
aut["淳"].append("みんなのpython")
aut["柴田　淳"].append("みんなのpython")
aut["しばたりょう"].append("みんなのpython")
aut["し"].append("みんなのpython")
aut["しばた"].append("みんなのpython")
aut["りょう"].append("みんなのpython")
aut["しばた　りょう"].append("みんなのpython")
aut["藤田博司"].append("「集合と位相」をなぜ学ぶのか　数学の基礎として根づくまでの歴史")
aut["イジィ・マトウシェク"].append("33の素敵な数学小景　フィボナッチ数、タイル張り、アルゴリズムを線形代数で眺めてみると")
aut["田島一郎"].append("one point イプシロンーデルタ")
aut["Nicholas J. Higham"].append("The Princeton Companion to Applied Mathematics")
aut["Mark R. Dennis"].append("The Princeton Companion to Applied Mathematics")
aut["Paul Glendinning"].append("The Princeton Companion to Applied Mathematics")
aut["Paul A. Martin"].append("The Princeton Companion to Applied Mathematics")
aut["吉田武"].append("オイラーの贈物 人類の至宝ｅｉπ＝−１を学ぶ 新装版")
aut["薩摩順吉"].append("キーポイント線形代数　２")
aut["四ツ谷晶二"].append("キーポイント線形代数　２")
aut["小形正男"].append("キーポイント多変数の微分積分７")
aut["R.J・ウィルソン"].append("グラフ理論入門原書第4版")
aut["千葉逸人"].append("これならわかる工学部で学ぶ数学")
aut["金谷健一"].append("これならわかる最適化数学　基礎原理から計算手法まで")
aut["野崎昭弘"].append("コンピュータサイエンス大学講座10　離散系の数学")
aut["国吉秀夫"].append("サイエンスライブラリ理工系の数学群論入門 （新訂版）")
aut["皆本晃弥"].append("スッキリわかる線形代数演習ー解答例・評価基準つきー")
aut["チャート研究所"].append("チャート式　基礎と演習数学Ⅰ+A")
aut["チャート研究所"].append("チャート式　基礎と演習数学Ⅱ+B")
aut["チャート研究所"].append("チャート式　基礎と演習数学Ⅲ")
aut["近藤至徳"].append("テーマ別演習①　入試数学の掌握　総論編")
aut["近藤至徳"].append("テーマ別演習②　入試数学の掌握　各論錬磨編")
aut["近藤至徳"].append("テーマ別演習③　入試数学の掌握　各論実戦編")
aut["赤塚不二夫"].append("ニャロメのおもしろ数学教室")
aut["寺澤順"].append("はじめてのルベーグ積分")
aut["大田春外"].append("はじめよう位相空間")
aut["ティモシー・ガワーズ"].append("プリンストン数学大全")
aut["結城浩"].append("プログラマの数学第2版")
aut["松田修"].append("ベクトル空間からはじめる抽象代数入門　群・体・テンソルまで")
aut["J.ヨスト"].append("ポストモダン解析学")
aut["高橋信　"].append("マンガでわかる線形代数")
aut["米田元"].append("ライブラリ演習新数学大系S3　理工基礎　演習微分積分")
aut["金子晃"].append("ライブラリ数理・情報系の数学講義新巻１　基礎演習　線形代数")
aut["竹尾富貴子"].append("ライブラリ数理・情報系の数学講義新巻２　基礎演習　微分積分")
aut["金子晃"].append("ライブラリ数理・情報系の数学講義新巻２　基礎演習　微分積分")
aut["海老原円"].append("ライブラリ例題から展開する大学数学　別巻①　例題から展開する線形代数演習")
aut["加藤文元"].append("宇宙と宇宙をつなぐ数学 = Mathematics that bridges universes : IUT理論の衝撃")
aut["押切源一"].append("演習　線形代数")
aut["今井秀雄"].append("演習　線形代数")
aut["大野芳希"].append("演習　線形代数")
aut["稲葉尚志"].append("演習　線形代数改訂版")
aut["野澤宗平"].append("演習　線形代数改訂版")
aut["村上正康"].append("演習　線形代数改訂版")
aut["坂和正敏"].append("応用解析学の基礎<複素解析・フーリエ解析・ラプラス変換>")
aut["永田靖"].append("科学のことばとしての数学　統計学のための数学入門30講")
aut["柴田正和"].append("科学者・技術者のための基礎線形代数と固有値問題")
aut["日本数学会"].append("岩波数学辞典第4版")
aut["青本和彦"].append("岩波数学入門書")
aut["茂木勇"].append("基礎演習シリーズ　線形代数")
aut["上野健爾"].append("岩波数学入門書")
aut["間下克哉"].append("基礎演習シリーズ　線形代数")
aut["加藤和也"].append("岩波数学入門書")
aut["神保道夫"].append("岩波数学入門書")
aut["砂田利一"].append("岩波数学入門書")
aut["高橋洋一郎"].append("岩波数学入門書")
aut["深谷賢治"].append("岩波数学入門書")
aut["保野博"].append("岩波数学入門書")
aut["室田一雄"].append("岩波数学入門書")
aut["斎藤正彦"].append("基礎数学１　線形代数入門")
aut["松本幸夫"].append("基礎数学５　多様体の基礎")
aut["杉浦光夫"].append("基礎数学７　解析演習")
aut["清水英男"].append("基礎数学７　解析演習")
aut["金子晃"].append("基礎数学７　解析演習")
aut["岡本和夫"].append("基礎数学７　解析演習")
aut["寺田文行"].append("基本演習ライブラリー１　基本演習線形代数")
aut["木村宣昭"].append("基本演習ライブラリー１　基本演習線形代数")
aut["寺田文行"].append("基本演習ライブラリー２　基本演習微分積分")
aut["坂田泩"].append("基本演習ライブラリー２　基本演習微分積分")
aut["園田英徳"].append("幾何学的に理解する物理数学")
aut["E.クライツィグ"].append("技術者のための高等数学１　常微分方程式原書第5版")
aut["吉田武"].append("虚数の情緒ー中学生からの全方位独学法")
aut["村上正康"].append("教養の線形代数")
aut["佐藤恒雄"].append("教養の線形代数")
aut["野澤宗平"].append("教養の線形代数")
aut["稲葉尚志"].append("教養の線形代数")
aut["小林昭七"].append("曲線と曲面の微分幾何（改訂版）")
aut["小倉久和"].append("形式言語と有限オートマトン入門―例題を中心とした情報の離散数学")
aut["神永正博"].append("計算力をつける微分積分問題集")
aut["藤田育嗣"].append("計算力をつける微分積分問題集")
aut["マイケル・ホルト"].append("芸術における数学")
aut["中岡宏之"].append("圏論の技法ーアーベル圏と三角圏でのホモロジー代数ー")
aut["西郷甲矢人"].append("圏論の道案内　矢印で描く数学の世界")
aut["能美十三"].append("圏論の道案内　矢印で描く数学の世界")
aut["圏論の歩き方委員会"].append("圏論の歩き方")
aut["赤攝也"].append("現代数学概論")
aut["中村力"].append("試せ実力！目指せ1級！　数学検定1級実践演習")
aut["寺沢寛一"].append("自然科学省のための数学概論〔増訂版〕")
aut["江川博康"].append("弱点克服　大学数学の計算問題")
aut["水田義弘"].append("詳解演習　線形代数　詳解演習ライブラリⅡ１")
aut["水田義弘"].append("詳解演習　微分積分　詳解演習ライブラリⅡ２")
aut["塹江誠夫"].append("詳説演習　線形代数学")
aut["福島雅夫"].append("情報数学講座12　計算幾何学")
aut["茂木俊秀"].append("情報数学講座14　最適化の手法")
aut["茂木俊秀"].append("情報数学講座12　計算幾何学")
aut["福島雅夫"].append("情報数学講座14　最適化の手法")
aut["小平邦彦"].append("新・数学の学び方")
aut["清史弘"].append("新数学Plus Elite 数学Ⅲ")
aut["川久保勝夫"].append("新装版　線形代数学")
aut["一樂重雄"].append("新版　集合と位相ーそのまま使える答えの書き方")
aut["寺田文行"].append("新版演習数学ライブラリⅡ２　新版　演習微分積分")
aut["坂田泩"].append("新版演習数学ライブラリⅡ２　新版　演習微分積分")
aut["石川聡彦"].append("人工知能プログラミングのための数学がわかる本")
aut["梶原健"].append("図で整理！　例題で納得！　線形空間入門")
aut["木村光一"].append("数学　微分方程式・複素整数　分野別標準問題精講")
aut["S・マックレーン"].append("数学ーその形式と機能")
aut["結城浩"].append("数学ガール　ガロア理論")
aut["結城浩"].append("数学ガール 乱択アルゴリズム")
aut["結城浩"].append("数学シリーズ　微分積分学")
aut["内田伏一"].append("数学シリーズ 集合と位相")
aut["日本評論社"].append("数学セミナー11　コンピュータにできる数字・できない数字")
aut["エドワード・フレンケル"].append("数学の大統一に挑む")
aut["小谷元子"].append("数学者が読んでいる本ってどんな本")
aut["本田雅成"].append("数理・情報系のための整数論講義")
aut["戸次大介"].append("数理論理学")
aut["原啓介"].append("線形性・固有値・テンソル　<線形代数>応用への最短コース")
aut["長谷川浩司"].append("線形代数 Linear Algebra改訂版")
aut["高崎金久"].append("線形代数とネットワーク")
aut["尼野一夫"].append("線形代数演習[新訂版]　数学演習ライブラリーⅡ１")
aut["横井英夫"].append("線形代数演習[新訂版]　数学演習ライブラリーⅡ１")
aut["松谷茂樹"].append("線形代数学周遊ー応用をめざして")
aut["佐武一郎"].append("数学選書　線形代数学　（新装版）")
aut["寺田文行"].append("線形代数増訂版　サイエンスライブラリ理工系の数学ー２３")
aut["竹内外史"].append("層・圏・トポスー現代的集合を求めて")
aut["原啓介"].append("測度・確率・ルベーグ積分ー応用への最短コース")
aut["室田一雄"].append("朝倉 数学ハンドブック 応用編")
aut["楠岡成雄"].append("朝倉 数学ハンドブック 応用編")
aut["飯高茂"].append("朝倉 数学ハンドブック 応用編")
aut["高木貞治"].append("定本解析概論")
aut["落合卓四郎"].append("東大教授が語る、東大新入生のための数学ガイドブック")
aut["D・A・ハーヴィル"].append("統計のための行列代数　上")
aut["D・A・ハーヴィル"].append("統計のための行列代数　下")
aut["サイエンス社"].append("特集・線形代数の探求")
aut["笠原晧司"].append("微分積分学　サイエンスライブラリ数学Ⅱ１２")
aut["高瀬正仁"].append("微分積分学の史的展開　ライプニッツから高木貞治まで")
aut["一樂重雄"].append("微分方程式そのまま使える答えの書き方")
aut["一樂祥子"].append("微分方程式そのまま使える答えの書き方")
aut["菊池誠"].append("不完全性定理")
aut["堀川穎二"].append("複素関数論の要諦[新装版]")
aut["金谷健一"].append("理工学者が書いた数学の本　線形代数１")
aut["甘利俊一"].append("理工学者が書いた数学の本　線形代数１")
aut["サイエンス社"].append("臨時別冊・数理科学　数学的な感覚の探求")
aut["西崎真也"].append("論理と計算のしくみ")
aut["萩谷昌己"].append("論理と計算のしくみ")
aut["小谷善行"].append("コンピュータサイエンスで学ぶ論理回路とその設計数学シリーズ⑦　ゲーム計算メカニズム")
aut["甘利俊一"].append("情報幾何学の新展開")
aut["甘利俊一"].append("新版　情報幾何学の新展開")
aut["吉本昌"].append("series電気　電子　情報系７　半導体デバイス")
aut["松波弘之"].append("series電気　電子　情報系７　半導体デバイス")
aut["竹内薫"].append("ファインマン物理学を読むー力学と熱力学を中心として")
aut["前野晶弘"].append("よくわかる電磁気学")
aut["西森秀稔"].append("基本法則から読み解く物理学最前線18　量子アニーリングの基礎")
aut["大関真之"].append("基本法則から読み解く物理学最前線18　量子アニーリングの基礎")
aut["ファインマン"].append("光　熱　波動　ファインマン物理学<Ⅱ>")
aut["ファインマン"].append("電磁気学　ファインマン物理学<Ⅲ>")
aut["ファインマン"].append("電磁波と物性　ファインマン物理学<Ⅳ>")
aut["青山均"].append("秘伝の微積物理")
aut["ダニエル・ホワイトソン"].append("僕たちは、宇宙のことぜんぜんわからない―――この世で一番おもしろい宇宙入門")
aut["ジョージ・チャム"].append("僕たちは、宇宙のことぜんぜんわからない―――この世で一番おもしろい宇宙入門")
aut["吉田宜章"].append("量子情報理論第3版")
aut["佐川弘幸"].append("量子情報理論第3版")
aut["ファインマン"].append("量子力学　ファインマン物理学<Ⅴ>")
aut["ファインマン"].append("力学　ファインマン物理学<Ⅰ>")
aut["Paul J. Silvia"].append("How to Write a Lot: A Practical Guide to Productive Academic Writing")
aut["Michael Swan"].append("Practical English Usage (Practical English Usage, fourth edition) ")
aut["Paul J. Silvia"].append("Write It Up: Practical Strategies for Writing and Publishing Journal Articles")
aut["大西泰斗"].append("ネイティブスピーカーの英文法絶対基礎力")
aut["ポール・マクベイ"].append("ネイティブスピーカーの英文法絶対基礎力")
aut["小野義正"].append("ポイントで学ぶ科学英語論文の書き方")
aut["松崎久純"].append("英文ビジネスレターは40の構文ですべて書ける")
aut["エディテージ"].append("英文校正会社が教える 英語論文のミス100")
aut["杉山忠一"].append("英文法詳解ーA COMPREHENSIVE ENGLISH GRAMMARー")
aut["グレン・パケット"].append("科学論文の英語用法百科〈第1編〉よく誤用される単語と表現")
aut["グレン・パケット"].append("科学論文の英語用法百科〈第2編〉冠詞用法")
aut["大島さくら子"].append("的確に伝わる英文ビジネスEメール例文集")
aut["マーク・ピーターセン"].append("表現のための実践ロイヤル英文法")
aut["綿貫陽"].append("表現のための実践ロイヤル英文法")
aut["廣岡慶彦"].append("理科系のための学会・留学英会話テクニック")
aut["廣岡慶彦"].append("理科系のための実戦英語プレゼンテーション")
aut["廣岡慶彦"].append("理科系のための入門英語プレゼンテーション")
aut["金谷健一"].append("理数系のための技術英語練習帳")
aut["Christopher Manning"].append("FOUNDATIONS OF STATISTICAL NATURAL LANGUAGE PROCESSING")
aut["Hinrich Schuetze"].append("FOUNDATIONS OF STATISTICAL NATURAL LANGUAGE PROCESSING")
aut["涌井良幸"].append("これならわかる！ベイズ統計学")
aut["涌井貞美"].append("これならわかる！ベイズ統計学")
aut["永田靖"].append("サンプルサイズの決め方")
aut["馬場敬之"].append("スバラシク実力がつく！　統計学キャンパス・ゼミ")
aut["久地井茂"].append("スバラシク実力がつく！　統計学キャンパス・ゼミ")
aut["久保拓弥"].append("データ解析のための統計モデリング入門――一般化線形モデル・階層ベイズモデル・MCMC (確率と情報の科学)")
aut["豊田秀樹"].append("はじめての統計データ分析ーベイズ的<ポストP値時代>の統計学ー")
aut["渡辺澄夫"].append("ベイズ統計の理論と方法")
aut["高橋信"].append("マンガでわかる統計学")
aut["高橋信"].append("マンガでわかる統計学[因子分析編]")
aut["豊田秀樹"].append("基礎からのベイズ統計学　ハミルトニアンモンテカルロ法による実践的入門")
aut["東京大学教養学部統計学教室"].append("基礎統計学Ⅲ　自然科学の統計学")
aut["G.K.カンジ"].append("逆引き統計学実践統計テスト100")
aut["豊田秀樹"].append("共分散構造分析[入門編]ー構造方程式モデリング")
aut["南風原朝和"].append("心理統計学の基礎ー統合的理解のためにー")
aut["Mark M. Meerschaert"].append("数理モデリング入門ファイブステップ法　原著第4版")
aut["足立浩平"].append("多変量データ解析法　心理・教育・社会系のための入門")
aut["星野祟宏"].append("調査観察データの統計科学―因果推論・選択バイアス・データ融合 (シリーズ確率と情報の科学) 　")
aut["岡田謙介"].append("伝えるための心理統計ー効果量・信頼区間・検定力ー")
aut["大久保街亜"].append("伝えるための心理統計ー効果量・信頼区間・検定力ー")
aut["柳川堯"].append("統計スポットライト・シリーズ３　P値　その正しい理解と適用")
aut["東京大学数学部統計学教室"].append("統計学入門")
aut["永田靖"].append("統計方法のしくみ　正しく理解するための30の急所")
aut["石井友二郎"].append("入門はじめての時系列分析")
aut["石井貞夫"].append("入門はじめての時系列分析")
aut["永田靖"].append("入門統計解析法")
aut["細野泰彦"].append("品質管理テキスト第4版")
aut["坂本碩也"].append("品質管理テキスト第4版")
aut["関根嘉香"].append("品質管理の統計学　製造現場に生かす統計手法")
aut["デービット・G・ルーエンバーガー"].append("金融工学入門")
aut["大平英樹"].append("感情心理学・入門")
aut["今田純雄"].append("心理学の世界基礎編11　感情心理学ー感情研究の基礎とその展開")
aut["中村真"].append("心理学の世界基礎編11　感情心理学ー感情研究の基礎とその展開")
aut["古満伊里"].append("心理学の世界基礎編11　感情心理学ー感情研究の基礎とその展開")
aut["鈴木直人"].append("朝倉心理学講座10　感情心理学")
aut["椙山敬士"].append("ソフトウェアの著作権・特許権")
aut["可知豊"].append("ソフトウェアライセンスの基礎知識")
aut["Richard M.Stallman"].append("フリーソフトウェアと自由な社会 ―Richard M. Stallmanエッセイ集")
aut["古谷栄男"].append("改訂五版　知って得するソフトウェア特許・著作権")
aut["松下正"].append("改訂五版　知って得するソフトウェア特許・著作権")
aut["眞島宏明"].append("改訂五版　知って得するソフトウェア特許・著作権")
aut["鶴本祥文"].append("改訂五版　知って得するソフトウェア特許・著作権")
aut["中山信弘"].append("著作権法")
aut["スティーブ・マコネル"].append("CODECOMPLETE第2版上")
aut["Thomas H. Cormen Charles E. Leiserson Ronald L. Rivest  Clifford Stein"].append("Introduction to Algorithms")
aut["ピーター・ヴァン・ロイ"].append("コンピュータプログラミングの概念・技法・モデル")
aut["ゼイフ・ハリディ"].append("コンピュータプログラミングの概念・技法・モデル")
aut["デビット・トーマス"].append("システム開発の職人から名匠への近道　達人プログラマー")
aut["アンドリュー・ハント"].append("システム開発の職人から名匠への近道　達人プログラマー")
aut["ポール・マクジョーンズ"].append("プログラミング原論")
aut["アレクサンダー・ステバノフ"].append("プログラミング原論")
aut["横内寛文"].append("プログラム意味論　情報数学講座７")
aut["Benjamin C. Pierce"].append("型システム入門プログラミング言語と型の理論")
aut["中島震"].append("形式手法入門ロジックによるソフトウェア設計")
aut["ケント・ベック"].append("実装パターン")
aut["ジョン・ベントリー"].append("珠玉のプログラミング 本質を見抜いたアルゴリズムとデータ構造")
aut["Steven Levithan"].append("正規表現クックブック")
aut["Jan　Goyvaerts"].append("正規表現クックブック")
aut["マーチン・ファウラー"].append("UMLモデリングのエッセンス第3版")
aut["平澤章"].append("オブジェクト指向でなぜつくるのか第２版")
aut["ジェームス・R・トロット"].append("オブジェクト指向のこころ")
aut["アラン・シャロウェイ"].append("オブジェクト指向のこころ")
aut["バートランド・メイヤー"].append("オブジェクト指向入門 第2版 方法論・実践")
aut["バートランド・メイヤー"].append("オブジェクト指向入門第2版原則・コンセプト (IT Architect’Archive クラシックモダン・コンピューティング)")
aut["マット・ステファン"].append("ユースケース駆動開発実践ガイド　オブジェクト指向分析からSpringによる実装まで")
aut["ダグ・ローゼンバーグ"].append("ユースケース駆動開発実践ガイド　オブジェクト指向分析からSpringによる実装まで")
aut["黒住幸光"].append("Apache Strutsハンドブック")
aut["エリック・D・ドメイン"].append("ゲームとパズルの計算量")
aut["ロバート・A・ハーン"].append("ゲームとパズルの計算量")
aut["馬場真哉"].append("時系列分と状態空間モデルの基礎　RとStanで学ぶ理論と実装")
aut["A.V.エイホ"].append("コンパイラ―原理・技法・ツール")
aut["R.セシィ"].append("コンパイラ―原理・技法・ツール")
aut["辻野嘉宏"].append("情報工学入門選書10　コンパイラ")
aut["Peter van der Linden"].append("エキスパートCプログラミングー知られざるCの深層")
aut["James W.Grenning"].append("テスト駆動開発による組み込みプログラミング　C言語とオブジェクト指向で学ぶアジャイル設計")
aut["D.M.リッチー"].append("プログラミング言語C第２版")
aut["B.W.カーニハン"].append("プログラミング言語C第２版")
aut["花井志生"].append("モダンC言語プログラミング")
aut["Richard Reese"].append("詳説Cポインタ")
aut["由梨かおる"].append("新・解きながら学ぶC言語")
aut["三木孝行"].append("Python実践データ分析１００本ノック")
aut["下山輝昌"].append("Python実践データ分析１００本ノック")
aut["松田雄馬"].append("Python実践データ分析１００本ノック")
aut["須藤明良"].append("スッキリわかるPython入門")
aut["国本大悟"].append("スッキリわかるPython入門")
aut["高橋麻奈"].append("やさしいPython")
aut["Bill Lubanovic"].append("入門Python３")
aut["Rabdtzal L. Schwar Tom Phoenix brian d foy"].append("第5版初めてのPerl")
aut["P.J.ワインバーガー"].append("プログラミング言語AWK")
aut["ジョシュア・ブロック"].append("Effective Java 第2版")
aut["中山清喬"].append("スッキリわかるJava入門")
aut["国本大悟"].append("スッキリわかるJava入門")
aut["中山清喬"].append("スッキリわかるJava入門実践編")
aut["結城浩"].append("増補改訂版Java言語で学ぶデザインパターン入門")
aut["千葉滋"].append("2週間でできる！スクリプト言語の作り方")
aut["松浦智之"].append("覚えて便利今すぐ使える！　シェルスクリプトシンプルレシピ54")
aut["Paolo Perrotta"].append("メタプログラミングRuby")
aut["Kent Beck"].append("リファクタリング：Rubyエディション")
aut["Jay Fields"].append("リファクタリング：Rubyエディション")
aut["Martin Fowler"].append("リファクタリング：Rubyエディション")
aut["Shane Harvie"].append("リファクタリング：Rubyエディション")
aut["株式会社TENTO＆できるシリーズ編集部"].append("子どもと学ぶScratch3プログラミング入門")
aut["山本光"].append("親子でかんたん　スクラッチプログラミングの図鑑")
aut["松下孝太郎"].append("親子でかんたん　スクラッチプログラミングの図鑑")
aut["藤本亮"].append("現場で使えるSQL第2版")
aut["小野哲"].append("現場で使えるSQL第2版")
aut["本橋智光"].append("前処理大全［データ分析のためのSQL/R/Python実践テクニック］")
aut["濱野純"].append("入門Git")
aut["Conrad Barski"].append("Land of Lisp")
aut["吉野一"].append("法律人工知能")
aut["谷口秀大"].append("イラストで学ぶ人工知能概論")
aut["松尾豊"].append("人工知能は人間を超えるか")
aut["人工知能の基礎"].append("小林一郎")
aut["新田克己"].append("知識と推論")
aut["岩波データサイエンス刊行委員会"].append("岩波データサイエンス②　統計的自然言語処理ーことばを扱う機械")
aut["奥村学"].append("自然言語処理の基礎")
aut["天野真家"].append("自然言語処理 (IT Text)")
aut["宇津呂武仁"].append("自然言語処理 (IT Text)")
aut["成田真澄"].append("自然言語処理 (IT Text)")
aut["福本淳"].append("自然言語処理 (IT Text)")
aut["石崎俊"].append("自然言語処理 (IT Text)")
aut["長尾真"].append("岩波講座ソフトウェア科学15　自然言語処理")
aut["奥村学"].append("自然言語処理シリーズ８　トピックモデルによる統計的潜在意味解析")
aut["麻生英樹"].append("深層学習 Deep Learning")
aut["安田宗樹"].append("深層学習 Deep Learning")
aut["前田新一"].append("深層学習 Deep Learning")
aut["岡野原大輔"].append("深層学習 Deep Learning")
aut["岡谷貴之"].append("深層学習 Deep Learning")
aut["久保陽太郎"].append("深層学習 Deep Learning")
aut["ボレガラ・ダヌシカ"].append("深層学習 Deep Learning")
aut["岡谷貴之"].append("深層学習")
aut["Yoav Goldberg"].append("自然言語処理のための深層学習")
aut["鈴木潤"].append("深層学習による自然言語処理")
aut["海野裕也"].append("深層学習による自然言語処理")
aut["坪井裕太"].append("深層学習による自然言語処理")
aut["巣籠悠輔"].append("詳解 ディープラーニング ~TensorFlow・Kerasによる時系列データ処理~")
aut["斎藤康毅"].append("ゼロから作るDeep　Learning　自然言語処理編")
aut["橋本幸士"].append("ディープラーニングと物理学")
aut["田中章詞"].append("ディープラーニングと物理学")
aut["富谷昭夫"].append("ディープラーニングと物理学")
aut["数理科学"].append("機械学習の数理ー数理的背景と実世界との関わりに迫る")
aut["鈴木穣"].append("統計的機械学習の数理100問 with Python ")
aut["足立悠"].append("機械学習のための「前処理」入門")
aut["高村大也"].append("自然言語処理シリーズ１　言語処理のための機械学習入門")
aut["吉本潤一郎"].append("これからの強化学習")
aut["保田俊行"].append("これからの強化学習")
aut["森本淳"].append("これからの強化学習")
aut["森村哲郎"].append("これからの強化学習")
aut["目黒豊美"].append("これからの強化学習")
aut["宮崎和光"].append("これからの強化学習")
aut["南泰浩"].append("これからの強化学習")
aut["松井藤五郎"].append("これからの強化学習")
aut["前田新一"].append("これからの強化学習")
aut["銅谷賢治"].append("これからの強化学習")
aut["坪井裕太"].append("これからの強化学習")
aut["杉本徳和"].append("これからの強化学習")
aut["黒江康明"].append("これからの強化学習")
aut["大倉和博"].append("これからの強化学習")
aut["伊藤真"].append("これからの強化学習")
aut["飯間等"].append("これからの強化学習")
aut["荒井幸代"].append("これからの強化学習")
aut["麻生英樹"].append("これからの強化学習")
aut["浅田稔"].append("これからの強化学習")
aut["白川真一"].append("これからの強化学習")
aut["澁谷長史"].append("これからの強化学習")
aut["牧野貴樹"].append("これからの強化学習")
aut["マイクロソフト公式"].append("CODECOMPLETE第2版下")
aut["Greg Wilson"].append("Making Software")
aut["Andy Oram"].append("Making Software")
aut["技術評論社"].append("Software Design総集編1990▶2000　11年分のバックナンバーを大収録")
aut["ティモシー・リスター"].append("ソフトウェアエンジニアリング論文集80’ｓデマルコ・セレクション")
aut["トム・デマルコ"].append("ソフトウェアエンジニアリング論文集80’ｓデマルコ・セレクション")
aut["野田夏子"].append("ソフトウェアテクノロジ－４　ソフトウェアアーキテクチャ")
aut["岸知二"].append("ソフトウェアテクノロジ－４　ソフトウェアアーキテクチャ")
aut["アラン・M.デービス"].append("ソフトウェア開発201の鉄則")
aut["玉井哲雄"].append("ソフトウェア社会のゆくえ")
aut["SQuBOK策定部会"].append("ソフトウェア品質知識体系ガイド第2版")
aut["Ivar Jacobson"].append("モダン・ソフトウェアエンジニアリング")
aut["Harold Bud Lawson"].append("モダン・ソフトウェアエンジニアリング")
aut["Pan-Wei Ng"].append("モダン・ソフトウェアエンジニアリング")
aut["Paul E. McMahon,"].append("モダン・ソフトウェアエンジニアリング")
aut["Michael Goedicke"].append("モダン・ソフトウェアエンジニアリング")
aut["横川智教"].append("レクチャーノート/ソフトウェア学42　ソフトウェア工学の基礎ⅩⅩⅢ")
aut["森崎修司"].append("レクチャーノート/ソフトウェア学44　ソフトウェア工学の基礎ⅩⅩⅤ")
aut["伊藤恵"].append("レクチャーノート/ソフトウェア学45　ソフトウェア工学の基礎ⅩⅩⅥ")
aut["阿萬裕久"].append("レクチャーノート/ソフトウェア学42　ソフトウェア工学の基礎ⅩⅩⅢ")
aut["大平雅雄"].append("レクチャーノート/ソフトウェア学44　ソフトウェア工学の基礎ⅩⅩⅤ")
aut["神谷年洋"].append("レクチャーノート/ソフトウェア学45　ソフトウェア工学の基礎ⅩⅩⅥ")
aut["長尾真"].append("岩波ソフトウェア科学14　知識と推論")
aut["独立行政法人情報処理推進機構技術本部ソフトウェア・エンジニアリング・センター"].append("共通フレーム2013～経営者、業務部門とともに取り組む「使える」システムの実践～")
aut["Mitchell Hashimoto"].append("実践Vagrant")
aut["ロジャーS.プレスマン"].append("実践ソフトウェアエンジニアリングーソフトウェアプロフェッショナルのための基本知識")
aut["Daniel Jackson"].append("抽象によるソフトウェア設計　Alloyで始める形式手法")
aut["田中英和"].append("この1冊でよくわかる　ソフトウェアテストの教科書")
aut["石原一宏"].append("この1冊でよくわかる　ソフトウェアテストの教科書")
aut["WACATE実行委員会"].append("ソフトウェアテスティングマニアックス１")
aut["WACATE実行委員会"].append("ソフトウェアテスティングマニアックス２")
aut["ケント・ベック"].append("テスト駆動開発入門")
aut["ITのプロ46　三好康之"].append("EXAMPRESS情報処理教科書　プロジェクトマネージャ")
aut["三好康之"].append("ITエンジニアのための【業務知識】がわかる本[第3版]")
aut["承地恒一"].append("WBS/EVMによるITプロジェクトマネジメント")
aut["山戸昭三"].append("WBS/EVMによるITプロジェクトマネジメント")
aut["マイク・コーン"].append("アジャイルな見積りと計画づくり ~価値あるソフトウェアを育てる概念と技法~")
aut["大森久美子"].append("ずっと受けたかったソフトウェア開発管理の集中研修")
aut["高橋宗雄"].append("ソフトウェアマネジメントモデル入門")
aut["山田茂"].append("ソフトウェアマネジメントモデル入門")
aut["森崎修二"].append("なぜ重大な問題を見逃すのか？間違いだらけの設計レビュー")
aut["山本政樹"].append("ビジネスプロセスの教科ーアイデアを「実行力」に転換する方法")
aut["加藤昭吉"].append("計画の科学")
aut["Robert C. Newbold"].append("時間に遅れないプロジェクトマネジメントー制約理論の応用ー")
aut["フレデリック・P・ブルックスJr"].append("人月の神話")
aut["妻木俊彦"].append("要求工学概論―要求工学の基本概念から応用まで")
aut["白銀純子"].append("要求工学概論―要求工学の基本概念から応用まで")
aut["大西淳"].append("要求工学概論―要求工学の基本概念から応用まで")
aut["本位田真"].append("要求工学概論―要求工学の基本概念から応用まで")
aut["平田研二"].append("はじめての制御工学")
aut["佐藤和也"].append("はじめての制御工学")
aut["平元和彦"].append("はじめての制御工学")
aut["デービット・G・ルーエンバーガー"].append("金融工学入門")
aut["橋本昭洋"].append("情報工学入門選書７　計算機アーキテクチャ")
aut["藤井信生"].append("アナログ電子回路")
aut["EMC　Education Services"].append("ストレージの原則と技術")
aut["西野友年"].append("今度こそわかる量子コンピューター")
aut["大久保英嗣　"].append("新世代工学シリーズ　オペレーティングシステム")
aut["Mike Gancarz"].append("ＵＮＩＸという考え方 その設計思想と哲学")
aut["Peter H. Salus"].append("UNIXの1/4世紀")
aut["AT＆Tベル研究所"].append("UNIX原典―AT&Tベル研のUNIX開発者自身によるUNIX公式解説書")
aut["戸根勤"].append("ネットワークはなぜつながるのか●知っておきたいTCP/IP、LAN、光ファイバの基礎知識●")
aut["Andrew S. Tanenbaum"].append("Computer Networks Fifth Edition")
aut["David j. Wetherall"].append("Computer Networks Fifth Edition")
aut["森大二郎"].append("検索エンジンはなぜ見つけるのか●知っておきたいウェブ情報検索の基礎知識")
aut["水野忠則"].append("未来へつなぐデジタルシリーズ　分散システム31第二版")
aut["真鍋義文"].append("情報工学レクチャーシリーズ　分散処理システム")
aut["谷口秀夫"].append("ITtext 分散処理 ")
aut["土屋達弘"].append("ディペンダブルシステム―高信頼システム実現のための耐故障・検証・テスト技術")
aut["米田友洋"].append("ディペンダブルシステム―高信頼システム実現のための耐故障・検証・テスト技術")
aut["梶原誠司"].append("ディペンダブルシステム―高信頼システム実現のための耐故障・検証・テスト技術")
aut["佐々木良一"].append("ITリスク学　「情報セキュリティ」を越えて")
aut["手塚悟"].append("情報セキュリティの基礎２")
aut["徳永拓之"].append("日本語入力を支える技術")
aut["杉山将"].append("異常検知と変化検知")
aut["井手剛"].append("異常検知と変化検知")
aut["元田浩"].append("ITtext データマイニングの基礎")
aut["津本周作"].append("ITtext データマイニングの基礎")
aut["山口高平"].append("ITtext データマイニングの基礎")
aut["沼尾正行"].append("ITtext データマイニングの基礎")
aut["Q. Ethan McCallum"].append("バッドデータハンドブック ―データにまつわる問題への19の処方箋 ")
aut["Steven S. Skiena"].append("データサイエンス設計マニュアル")
aut["小林進一郎"].append("ことばのデータサイエンス")
aut["技術評論社"].append("データサイエンティスト養成読本")
aut["Tim Menzies"].append("Perspectives on Data Science for Software Engineering ")
aut["Laurie Williams"].append("Perspectives on Data Science for Software Engineering ")
aut["Thomas Zimmermann"].append("Perspectives on Data Science for Software Engineering ")
aut["三中信宏"].append("思考の世界ー曼荼羅で読み解くデータ解析の基礎")
aut["知泉潔"].append("マルチエージェントのためのデータ解析")
aut["岩波データサイエンス刊行委員会"].append("岩波データサイエンス５　スパートモデリングと多変量データ解析")
aut["福島真太朗"].append("UsefuPシリーズ２　データ分析プロセス")
aut["Christian Bird"].append("The Art and Science of Analyzing Software Data")
aut["Tim Menzies"].append("The Art and Science of Analyzing Software Data")
aut["Thomas Zimmermann"].append("The Art and Science of Analyzing Software Data")
aut["Jeff Hammerbacher"].append("Beautiful Data")
aut["Toby Segaran"].append("Beautiful Data")
aut["那須川哲哉"].append("テキストマイニングを使う技術/作る技術")
aut["ローネン・フェルドマン"].append("テキストマイニングハンドブック")
aut["平井有三"].append("はじめてのパターン認識")
aut["Andreas Zeller"].append("デバッグの理論と実践")
aut["柴山潔"].append("コンピュータサイエンスで学ぶ論理回路とその設計")
aut["嵩忠雄"].append("情報工学入門選書6　情報と符号の理論入門")
aut["都倉信樹"].append("オートマトンと形式主語")
aut["野村俊一"].append("点過程の時系列解析")
aut["近江祟宏"].append("点過程の時系列解析")
aut["岩波書店"].append("岩波データサイエンス６　時系列解析ー状態空間モデル・因果解析・ビジネス応用")
aut["原田達也"].append("画像認識")
aut["岡野原大輔"].append("高速文字列解析の世界――データ圧縮・全文検索・テキストマイニング")
aut["伊庭斉志"].append("複雑系のシミュレーション―Swarmによるマルチエージェント・システム")
aut["小山聡"].append("ヒューマンコンビュテーションとクラウドソーシング")
aut["馬場雪乃"].append("ヒューマンコンビュテーションとクラウドソーシング")
aut["鹿島久嗣"].append("ヒューマンコンビュテーションとクラウドソーシング")
aut["瓜生真也"].append("基礎からわかる時系列分析―Rで実践するカルマンフィルタ・MCMC・粒子フィルタ― Data Science Library")
aut["牧山幸史　"].append("基礎からわかる時系列分析―Rで実践するカルマンフィルタ・MCMC・粒子フィルタ― Data Science Library")
aut["萩原淳一郎"].append("基礎からわかる時系列分析―Rで実践するカルマンフィルタ・MCMC・粒子フィルタ― Data Science Library")
aut["野村俊一"].append("カルマンフィルタ")
aut["産業技術総合研究所システム検証研究センター"].append("モデル検査 初級編―基礎から実践まで4日で学べる ")
aut["中島震"].append("SPINモデル検査")
aut["廣瀬明"].append("複素ニューラルネットワーク第2版")
aut["後藤順哉"].append("オペレーションズ・リサーチシリーズ５　意思決定のための数理モデル入門")
aut["今野浩"].append("オペレーションズ・リサーチシリーズ５　意思決定のための数理モデル入門")
aut["井上樹"].append("ダイアグラム別UML徹底活用第2版")
aut["G・ポリア"].append("いかにして問題をとくか")
aut["芳沢光雄"].append("いかにして問題を解くか　実践活用編")
aut["ジェラルド・M・ワインバーグ"].append("コンサルタントの道具箱")
aut["アラン・ブリンクリ・B"].append("シカゴ大学教授法ハンドブック")
aut["デッサンツ・M"].append("シカゴ大学教授法ハンドブック")
aut["フラム・C"].append("シカゴ大学教授法ハンドブック")
aut["フレミング・C"].append("シカゴ大学教授法ハンドブック")
aut["フォースィ・E.ロスチャイルド"].append("シカゴ大学教授法ハンドブック")
aut["ウォルター・ディック"].append("はじめてのインストラクショナルデザイン")
aut["ルー・ケアリー"].append("はじめてのインストラクショナルデザイン")
aut["マリリン・バーンズ"].append("考える練習をしよう (子どものためのライフ・スタイル) ")
aut["マーサ・ウェストン"].append("考える練習をしよう (子どものためのライフ・スタイル) ")
aut["稲垣忠"].append("授業設計マニュアル")
aut["常盤拓司"].append("大学１年生からのプロジェクト学習の始め方")
aut["鈴木克明"].append("授業設計マニュアル")
aut["西山敏樹"].append("大学１年生からのプロジェクト学習の始め方")
aut["トニー・ブザン"].append("脳の力を強化する思考技術　ザ・マインドマップ")
aut["野矢茂樹"].append("論理トレーニング１０１題")
aut["ロース・ファンデル・スコール"].append("デザイン思考の教科書ー欧州トップスクールが教えるイノベーションの技術ー")
aut["イェレ・ザイルストラ"].append("デザイン思考の教科書ー欧州トップスクールが教えるイノベーションの技術ー")
aut["ヤープ・ダールハウゼン"].append("デザイン思考の教科書ー欧州トップスクールが教えるイノベーションの技術ー")
aut["アネミック・ファン・ブイエン"].append("デザイン思考の教科書ー欧州トップスクールが教えるイノベーションの技術ー")
aut["佐藤雅昭"].append("なぜあなたの研究は進まないのか？")
aut["島岡要"].append("やるべきことが見えてくる　研究者の仕事術　プロフェッショナル根性論")
aut["郡健二郎"].append("科研費　採択される3要素ーアイデア・業績・見栄え")
aut["児島将康"].append("科研費獲得のコツ改訂版第3版")
aut["N.C.Barford"].append("実験精度と誤差ー測定の確からしさとは何か")
aut["メラニー・ミッチェル"].append("ガイドツアー複雑系の世界ーサンタフェ研究所講義ノートから")
aut["ガー・レイノルズ"].append("プレゼンテーションzen")
aut["久保田浪之介"].append("研究者のための国際学会プレゼンテーション")
aut["藤沢晃治"].append("「分かりやすい表現」の技術 意図を正しく伝えるための16のルール")
aut["Matt Carter"].append("Designing Science Presentations: A Visual Guide to Figures, Papers, Slides, Posters, and More ")
aut["KathrynL. Allen"].append("スタディスキルズー卒研・卒論から博士論文まで、研究生活サバイバルガイド")
aut["ポール・J・シルヴィア"].append("できる研究者の論文作成メソッド")
aut["佐藤雅昭"].append("なぜあなたは論文が書けないのか？")
aut["藤田英時"].append("メール文章力の基本")
aut["児島将康"].append("科研費申請書の赤ペン添削ハンドブック")
aut["奥村晴彦"].append("改訂第6版　LATEX2ε　美文書作成入門")
aut["黒木祐介"].append("改訂第6版　LATEX2ε　美文書作成入門")
aut["日本エディタースクール"].append("原稿編集ルールブック　原稿整理のポイント")
aut["神垣あゆみ"].append("考えすぎて書けない人のための1分間メール術")
aut["本田勝一"].append("新装版日本語の作文技術")
aut["阿部圭一"].append("明文術　伝わる日本語の書き方")
aut["木下是雄"].append("理科系の作文技術")
aut["中田亭"].append("理系のための「即効！」卒業論文術")
aut["吉村宗之"].append("うまいウイスキーの科学")
aut["山本武司"].append("うまいビールの科学")
aut["Testosterone"].append("筋トレが最強のソリューションである")
aut["Testosterone"].append("人生の99.9％の問題は、筋トレで解決できる！")
aut["稲見昌彦"].append("スーパーヒューマン誕生！")
aut["ふ"].append("「集合と位相」をなぜ学ぶのか　数学の基礎として根づくまでの歴史")
aut["い"].append("33の素敵な数学小景　フィボナッチ数、タイル張り、アルゴリズムを線形代数で眺めてみると")
aut["た"].append("one point イプシロンーデルタ")
aut["N"].append("The Princeton Companion to Applied Mathematics")
aut["M"].append("The Princeton Companion to Applied Mathematics")
aut["P"].append("The Princeton Companion to Applied Mathematics")
aut["よ"].append("オイラーの贈物 人類の至宝ｅｉπ＝−１を学ぶ 新装版")
aut["さ"].append("キーポイント線形代数　２")
aut["よ"].append("キーポイント線形代数　２")
aut["お"].append("キーポイント多変数の微分積分７")
aut["R"].append("グラフ理論入門原書第4版")
aut["ち"].append("これならわかる工学部で学ぶ数学")
aut["か"].append("これならわかる最適化数学　基礎原理から計算手法まで")
aut["の"].append("コンピュータサイエンス大学講座10　離散系の数学")
aut["く"].append("サイエンスライブラリ理工系の数学群論入門 （新訂版）")
aut["か"].append("スッキリわかる線形代数演習ー解答例・評価基準つきー")
aut["ち"].append("チャート式　基礎と演習数学Ⅰ+A")
aut["ち"].append("チャート式　基礎と演習数学Ⅱ+B")
aut["ち"].append("チャート式　基礎と演習数学Ⅲ")
aut["こ"].append("テーマ別演習①　入試数学の掌握　総論編")
aut["こ"].append("テーマ別演習②　入試数学の掌握　各論錬磨編")
aut["こ"].append("テーマ別演習③　入試数学の掌握　各論実戦編")
aut["あ"].append("ニャロメのおもしろ数学教室")
aut["て"].append("はじめてのルベーグ積分")
aut["お"].append("はじめよう位相空間")
aut["て"].append("プリンストン数学大全")
aut["ゆ"].append("プログラマの数学第2版")
aut["ま"].append("ベクトル空間からはじめる抽象代数入門　群・体・テンソルまで")
aut["J"].append("ポストモダン解析学")
aut["た"].append("マンガでわかる線形代数")
aut["よ"].append("ライブラリ演習新数学大系S3　理工基礎　演習微分積分")
aut["か"].append("ライブラリ数理・情報系の数学講義新巻１　基礎演習　線形代数")
aut["か"].append("ライブラリ数理・情報系の数学講義新巻２　基礎演習　微分積分")
aut["た"].append("ライブラリ数理・情報系の数学講義新巻２　基礎演習　微分積分")
aut["え"].append("ライブラリ例題から展開する大学数学　別巻①　例題から展開する線形代数演習")
aut["か"].append("宇宙と宇宙をつなぐ数学 = Mathematics that bridges universes : IUT理論の衝撃")
aut["お"].append("演習　線形代数")
aut["い"].append("演習　線形代数")
aut["おし"].append("演習　線形代数")
aut["む"].append("演習　線形代数改訂版")
aut["の"].append("演習　線形代数改訂版")
aut["い"].append("演習　線形代数改訂版")
aut["さ"].append("応用解析学の基礎<複素解析・フーリエ解析・ラプラス変換>")
aut["な"].append("科学のことばとしての数学　統計学のための数学入門30講")
aut["し"].append("科学者・技術者のための基礎線形代数と固有値問題")
aut["に"].append("岩波数学辞典第4版")
aut["あ"].append("岩波数学入門書")
aut["う"].append("岩波数学入門書")
aut["か"].append("岩波数学入門書")
aut["じ"].append("岩波数学入門書")
aut["す"].append("岩波数学入門書")
aut["た"].append("岩波数学入門書")
aut["ふ"].append("岩波数学入門書")
aut["ほ"].append("岩波数学入門書")
aut["む"].append("岩波数学入門書")
aut["も"].append("基礎演習シリーズ　線形代数")
aut["ま"].append("基礎演習シリーズ　線形代数")
aut["さ"].append("基礎数学１　線形代数入門")
aut["ま"].append("基礎数学５　多様体の基礎")
aut["す"].append("基礎数学７　解析演習")
aut["し"].append("基礎数学７　解析演習")
aut["か"].append("基礎数学７　解析演習")
aut["お"].append("基礎数学７　解析演習")
aut["て"].append("基本演習ライブラリー１　基本演習線形代数")
aut["き"].append("基本演習ライブラリー１　基本演習線形代数")
aut["て"].append("基本演習ライブラリー２　基本演習微分積分")
aut["さ"].append("基本演習ライブラリー２　基本演習微分積分")
aut["そ"].append("幾何学的に理解する物理数学")
aut["E"].append("技術者のための高等数学１　常微分方程式原書第5版")
aut["よ"].append("虚数の情緒ー中学生からの全方位独学法")
aut["む"].append("教養の線形代数")
aut["さ"].append("教養の線形代数")
aut["の"].append("教養の線形代数")
aut["い"].append("教養の線形代数")
aut["こ"].append("曲線と曲面の微分幾何（改訂版）")
aut["お"].append("形式言語と有限オートマトン入門―例題を中心とした情報の離散数学")
aut["か"].append("計算力をつける微分積分問題集")
aut["ふ"].append("計算力をつける微分積分問題集")
aut["ま"].append("芸術における数学")
aut["な"].append("圏論の技法ーアーベル圏と三角圏でのホモロジー代数ー")
aut["さ"].append("圏論の道案内　矢印で描く数学の世界")
aut["の"].append("圏論の道案内　矢印で描く数学の世界")
aut["け"].append("圏論の歩き方")
aut["せ"].append("現代数学概論")
aut["な"].append("試せ実力！目指せ1級！　数学検定1級実践演習")
aut["て"].append("自然科学省のための数学概論〔増訂版〕")
aut["え"].append("弱点克服　大学数学の計算問題")
aut["み"].append("詳解演習　線形代数　詳解演習ライブラリⅡ１")
aut["み"].append("詳解演習　微分積分　詳解演習ライブラリⅡ２")
aut["ほ"].append("詳説演習　線形代数学")
aut["ふ"].append("情報数学講座12　計算幾何学")
aut["も"].append("情報数学講座14　最適化の手法")
aut["も"].append("情報数学講座12　計算幾何学")
aut["ふ"].append("情報数学講座14　最適化の手法")
aut["こ"].append("新・数学の学び方")
aut["き"].append("新数学Plus Elite 数学Ⅲ")
aut["か"].append("新装版　線形代数学")
aut["ひ"].append("新版　集合と位相ーそのまま使える答えの書き方")
aut["て"].append("新版演習数学ライブラリⅡ２　新版　演習微分積分")
aut["さ"].append("新版演習数学ライブラリⅡ２　新版　演習微分積分")
aut["い"].append("人工知能プログラミングのための数学がわかる本")
aut["か"].append("図で整理！　例題で納得！　線形空間入門")
aut["き"].append("数学　微分方程式・複素整数　分野別標準問題精講")
aut["S"].append("数学ーその形式と機能")
aut["ゆ"].append("数学ガール　ガロア理論")
aut["ゆ"].append("数学ガール 乱択アルゴリズム")
aut["ゆ"].append("数学シリーズ　微分積分学")
aut["う"].append("数学シリーズ 集合と位相")
aut["に"].append("数学セミナー11　コンピュータにできる数字・できない数字")
aut["え"].append("数学の大統一に挑む")
aut["こ"].append("数学者が読んでいる本ってどんな本")
aut["ほ"].append("数理・情報系のための整数論講義")
aut["と"].append("数理論理学")
aut["は"].append("線形性・固有値・テンソル　<線形代数>応用への最短コース")
aut["は"].append("線形代数 Linear Algebra改訂版")
aut["た"].append("線形代数とネットワーク")
aut["あ"].append("線形代数演習[新訂版]　数学演習ライブラリーⅡ１")
aut["よ"].append("線形代数演習[新訂版]　数学演習ライブラリーⅡ１")
aut["ま"].append("線形代数学周遊ー応用をめざして")
aut["さ"].append("数学選書　線形代数学　（新装版）")
aut["て"].append("線形代数増訂版　サイエンスライブラリ理工系の数学ー２３")
aut["た"].append("層・圏・トポスー現代的集合を求めて")
aut["は"].append("測度・確率・ルベーグ積分ー応用への最短コース")
aut["む"].append("朝倉 数学ハンドブック 応用編")
aut["く"].append("朝倉 数学ハンドブック 応用編")
aut["い"].append("朝倉 数学ハンドブック 応用編")
aut["た"].append("定本解析概論")
aut["お"].append("東大教授が語る、東大新入生のための数学ガイドブック")
aut["D"].append("統計のための行列代数　上")
aut["D"].append("統計のための行列代数　下")
aut["さ"].append("特集・線形代数の探求")
aut["か"].append("微分積分学　サイエンスライブラリ数学Ⅱ１２")
aut["た"].append("微分積分学の史的展開　ライプニッツから高木貞治まで")
aut["ひ"].append("微分方程式そのまま使える答えの書き方")
aut["ひ"].append("微分方程式そのまま使える答えの書き方")
aut["き"].append("不完全性定理")
aut["ほ"].append("複素関数論の要諦[新装版]")
aut["か"].append("理工学者が書いた数学の本　線形代数１")
aut["あ"].append("理工学者が書いた数学の本　線形代数１")
aut["さ"].append("臨時別冊・数理科学　数学的な感覚の探求")
aut["に"].append("論理と計算のしくみ")
aut["は"].append("論理と計算のしくみ")
aut["こ"].append("コンピュータサイエンスで学ぶ論理回路とその設計数学シリーズ⑦　ゲーム計算メカニズム")
aut["あ"].append("情報幾何学の新展開")
aut["あ"].append("新版　情報幾何学の新展開")
aut["よ"].append("series電気　電子　情報系７　半導体デバイス")
aut["ま"].append("series電気　電子　情報系７　半導体デバイス")
aut["た"].append("ファインマン物理学を読むー力学と熱力学を中心として")
aut["ま"].append("よくわかる電磁気学")
aut["に"].append("基本法則から読み解く物理学最前線18　量子アニーリングの基礎")
aut["お"].append("基本法則から読み解く物理学最前線18　量子アニーリングの基礎")
aut["ふ"].append("光　熱　波動　ファインマン物理学<Ⅱ>")
aut["ふ"].append("電磁気学　ファインマン物理学<Ⅲ>")
aut["ふ"].append("電磁波と物性　ファインマン物理学<Ⅳ>")
aut["あ"].append("秘伝の微積物理")
aut["だ"].append("僕たちは、宇宙のことぜんぜんわからない―――この世で一番おもしろい宇宙入門")
aut["じ"].append("僕たちは、宇宙のことぜんぜんわからない―――この世で一番おもしろい宇宙入門")
aut["よ"].append("量子情報理論第3版")
aut["さ"].append("量子情報理論第3版")
aut["ふ"].append("量子力学　ファインマン物理学<Ⅴ>")
aut["ふ"].append("力学　ファインマン物理学<Ⅰ>")
aut["P"].append("How to Write a Lot: A Practical Guide to Productive Academic Writing")
aut["M"].append("Practical English Usage (Practical English Usage, fourth edition) ")
aut["P"].append("Write It Up: Practical Strategies for Writing and Publishing Journal Articles")
aut["お"].append("ネイティブスピーカーの英文法絶対基礎力")
aut["ぽ"].append("ネイティブスピーカーの英文法絶対基礎力")
aut["お"].append("ポイントで学ぶ科学英語論文の書き方")
aut["ま"].append("英文ビジネスレターは40の構文ですべて書ける")
aut["え"].append("英文校正会社が教える 英語論文のミス100")
aut["す"].append("英文法詳解ーA COMPREHENSIVE ENGLISH GRAMMARー")
aut["ぐ"].append("科学論文の英語用法百科〈第1編〉よく誤用される単語と表現")
aut["ぐ"].append("科学論文の英語用法百科〈第2編〉冠詞用法")
aut["お"].append("的確に伝わる英文ビジネスEメール例文集")
aut["ま"].append("表現のための実践ロイヤル英文法")
aut["に"].append("表現のための実践ロイヤル英文法")
aut["た"].append("理科系のための学会・留学英会話テクニック")
aut["た"].append("理科系のための実戦英語プレゼンテーション")
aut["た"].append("理科系のための入門英語プレゼンテーション")
aut["か"].append("理数系のための技術英語練習帳")
aut["C"].append("FOUNDATIONS OF STATISTICAL NATURAL LANGUAGE PROCESSING")
aut["H"].append("FOUNDATIONS OF STATISTICAL NATURAL LANGUAGE PROCESSING")
aut["わ"].append("これならわかる！ベイズ統計学")
aut["わ"].append("これならわかる！ベイズ統計学")
aut["な"].append("サンプルサイズの決め方")
aut["ば"].append("スバラシク実力がつく！　統計学キャンパス・ゼミ")
aut["く"].append("スバラシク実力がつく！　統計学キャンパス・ゼミ")
aut["く"].append("データ解析のための統計モデリング入門――一般化線形モデル・階層ベイズモデル・MCMC (確率と情報の科学)")
aut["と"].append("はじめての統計データ分析ーベイズ的<ポストP値時代>の統計学ー")
aut["わ"].append("ベイズ統計の理論と方法")
aut["た"].append("マンガでわかる統計学")
aut["た"].append("マンガでわかる統計学[因子分析編]")
aut["と"].append("基礎からのベイズ統計学　ハミルトニアンモンテカルロ法による実践的入門")
aut["と"].append("基礎統計学Ⅲ　自然科学の統計学")
aut["G"].append("逆引き統計学実践統計テスト100")
aut["と"].append("共分散構造分析[入門編]ー構造方程式モデリング")
aut["は"].append("心理統計学の基礎ー統合的理解のためにー")
aut["M"].append("数理モデリング入門ファイブステップ法　原著第4版")
aut["あ"].append("多変量データ解析法　心理・教育・社会系のための入門")
aut["ほ"].append("調査観察データの統計科学―因果推論・選択バイアス・データ融合 (シリーズ確率と情報の科学) 　")
aut["お"].append("伝えるための心理統計ー効果量・信頼区間・検定力ー")
aut["お"].append("伝えるための心理統計ー効果量・信頼区間・検定力ー")
aut["や"].append("統計スポットライト・シリーズ３　P値　その正しい理解と適用")
aut["と"].append("統計学入門")
aut["な"].append("統計方法のしくみ　正しく理解するための30の急所")
aut["い"].append("入門はじめての時系列分析")
aut["い"].append("入門はじめての時系列分析")
aut["な"].append("入門統計解析法")
aut["ほ"].append("品質管理テキスト第4版")
aut["さ"].append("品質管理テキスト第4版")
aut["せ"].append("品質管理の統計学　製造現場に生かす統計手法")
aut["で"].append("金融工学入門")
aut["お"].append("感情心理学・入門")
aut["い"].append("心理学の世界基礎編11　感情心理学ー感情研究の基礎とその展開")
aut["な"].append("心理学の世界基礎編11　感情心理学ー感情研究の基礎とその展開")
aut["ふ"].append("心理学の世界基礎編11　感情心理学ー感情研究の基礎とその展開")
aut["す"].append("朝倉心理学講座10　感情心理学")
aut["す"].append("ソフトウェアの著作権・特許権")
aut["か"].append("ソフトウェアライセンスの基礎知識")
aut["R"].append("フリーソフトウェアと自由な社会 ―Richard M. Stallmanエッセイ集")
aut["ふ"].append("改訂五版　知って得するソフトウェア特許・著作権")
aut["ま"].append("改訂五版　知って得するソフトウェア特許・著作権")
aut["ま"].append("改訂五版　知って得するソフトウェア特許・著作権")
aut["つ"].append("改訂五版　知って得するソフトウェア特許・著作権")
aut["な"].append("著作権法")
aut["す"].append("CODECOMPLETE第2版上")
aut["T"].append("Introduction to Algorithms")
aut["ぴ"].append("コンピュータプログラミングの概念・技法・モデル")
aut["ぜ"].append("コンピュータプログラミングの概念・技法・モデル")
aut["で"].append("システム開発の職人から名匠への近道　達人プログラマー")
aut["あ"].append("システム開発の職人から名匠への近道　達人プログラマー")
aut["ぽ"].append("プログラミング原論")
aut["あ"].append("プログラミング原論")
aut["よ"].append("プログラム意味論　情報数学講座７")
aut["B"].append("型システム入門プログラミング言語と型の理論")
aut["な"].append("形式手法入門ロジックによるソフトウェア設計")
aut["け"].append("実装パターン")
aut["じ"].append("珠玉のプログラミング 本質を見抜いたアルゴリズムとデータ構造")
aut["S"].append("正規表現クックブック")
aut["J"].append("正規表現クックブック")
aut["ま"].append("UMLモデリングのエッセンス第3版")
aut["ひ"].append("オブジェクト指向でなぜつくるのか第２版")
aut["じ"].append("オブジェクト指向のこころ")
aut["あ"].append("オブジェクト指向のこころ")
aut["ば"].append("オブジェクト指向入門 第2版 方法論・実践")
aut["ば"].append("オブジェクト指向入門第2版原則・コンセプト (IT Architect’Archive クラシックモダン・コンピューティング)")
aut["ま"].append("ユースケース駆動開発実践ガイド　オブジェクト指向分析からSpringによる実装まで")
aut["だ"].append("ユースケース駆動開発実践ガイド　オブジェクト指向分析からSpringによる実装まで")
aut["く"].append("Apache Strutsハンドブック")
aut["え"].append("ゲームとパズルの計算量")
aut["ろ"].append("ゲームとパズルの計算量")
aut["ば"].append("時系列分と状態空間モデルの基礎　RとStanで学ぶ理論と実装")
aut["A"].append("コンパイラ―原理・技法・ツール")
aut["R"].append("コンパイラ―原理・技法・ツール")
aut["つ"].append("情報工学入門選書10　コンパイラ")
aut["P"].append("エキスパートCプログラミングー知られざるCの深層")
aut["J"].append("テスト駆動開発による組み込みプログラミング　C言語とオブジェクト指向で学ぶアジャイル設計")
aut["D"].append("プログラミング言語C第２版")
aut["B"].append("プログラミング言語C第２版")
aut["は"].append("モダンC言語プログラミング")
aut["R"].append("詳説Cポインタ")
aut["ゆ"].append("新・解きながら学ぶC言語")
aut["み"].append("Python実践データ分析１００本ノック")
aut["し"].append("Python実践データ分析１００本ノック")
aut["ま"].append("Python実践データ分析１００本ノック")
aut["す"].append("スッキリわかるPython入門")
aut["く"].append("スッキリわかるPython入門")
aut["た"].append("やさしいPython")
aut["B"].append("入門Python３")
aut["R"].append("第5版初めてのPerl")
aut["P"].append("プログラミング言語AWK")
aut["じ"].append("Effective Java 第2版")
aut["な"].append("スッキリわかるJava入門")
aut["く"].append("スッキリわかるJava入門")
aut["な"].append("スッキリわかるJava入門実践編")
aut["ゆ"].append("増補改訂版Java言語で学ぶデザインパターン入門")
aut["ち"].append("2週間でできる！スクリプト言語の作り方")
aut["ま"].append("覚えて便利今すぐ使える！　シェルスクリプトシンプルレシピ54")
aut["P"].append("メタプログラミングRuby")
aut["K"].pend("リファクタリング：Rubyエディション")
aut["J"].append("リファクタリング：Rubyエディション")
aut["M"].append("リファクタリング：Rubyエディション")
aut["S"].append("リファクタリング：Rubyエディション")
aut["か"].append("子どもと学ぶScratch3プログラミング入門")
aut["や"].append("親子でかんたん　スクラッチプログラミングの図鑑")
aut["ま"].append("親子でかんたん　スクラッチプログラミングの図鑑")
aut["ふ"].append("現場で使えるSQL第2版")
aut["お"].append("現場で使えるSQL第2版")
aut["も"].append("前処理大全［データ分析のためのSQL/R/Python実践テクニック］")
aut["は"].append("入門Git")
aut["C"].append("Land of Lisp")
aut["よ"].append("法律人工知能")
aut["た"].append("イラストで学ぶ人工知能概論")
aut["ま"].append("人工知能は人間を超えるか")
aut["こ"].append("人工知能の基礎")
aut["に"].append("知識と推論")
aut["い"].append("岩波データサイエンス②　統計的自然言語処理ーことばを扱う機械")
aut["お"].append("自然言語処理の基礎")
aut["あ"].append("自然言語処理 (IT Text)")
aut["う"].append("自然言語処理 (IT Text)")
aut["な"].append("自然言語処理 (IT Text)")
aut["ふ"].append("自然言語処理 (IT Text)")
aut["い"].append("自然言語処理 (IT Text)")
aut["な"].append("岩波講座ソフトウェア科学15　自然言語処理")
aut["お"].append("自然言語処理シリーズ８　トピックモデルによる統計的潜在意味解析")
aut["あ"].append("深層学習 Deep Learning")
aut["や"].append("深層学習 Deep Learning")
aut["ま"].append("深層学習 Deep Learning")
aut["お"].append("深層学習 Deep Learning")
aut["お"].append("深層学習 Deep Learning")
aut["く"].append("深層学習 Deep Learning")
aut["ぼ"].append("深層学習 Deep Learning")
aut["お"].append("深層学習")
aut["Y"].append("自然言語処理のための深層学習")
aut["す"].append("深層学習による自然言語処理")
aut["う"].append("深層学習による自然言語処理")
aut["つ"].append("深層学習による自然言語処理")
aut["す"].append("詳解 ディープラーニング ~TensorFlow・Kerasによる時系列データ処理~")
aut["さ"].append("ゼロから作るDeep　Learning　自然言語処理編")
aut["は"].append("ディープラーニングと物理学")
aut["た"].append("ディープラーニングと物理学")
aut["と"].append("ディープラーニングと物理学")
aut["す"].append("機械学習の数理ー数理的背景と実世界との関わりに迫る")
aut["す"].append("統計的機械学習の数理100問 with Python ")
aut["あ"].append("機械学習のための「前処理」入門")
aut["た"].append("自然言語処理シリーズ１　言語処理のための機械学習入門")
aut["よ"].append("これからの強化学習")
aut["や"].append("これからの強化学習")
aut["も"].append("これからの強化学習")
aut["も"].append("これからの強化学習")
aut["め"].append("これからの強化学習")
aut["み"].append("これからの強化学習")
aut["み"].append("これからの強化学習")
aut["ま"].append("これからの強化学習")
aut["ま"].append("これからの強化学習")
aut["ど"].append("これからの強化学習")
aut["つ"].append("これからの強化学習")
aut["す"].append("これからの強化学習")
aut["く"].append("これからの強化学習")
aut["お"].append("これからの強化学習")
aut["い"].append("これからの強化学習")
aut["いい"].append("これからの強化学習")
aut["あ"].append("これからの強化学習")
aut["あそ"].append("これからの強化学習")
aut["あさ"].append("これからの強化学習")
aut["し"].append("これからの強化学習")
aut["しぶ"].append("これからの強化学習")
aut["まき"].append("これからの強化学習")
aut["ま"].append("CODECOMPLETE第2版下")
aut["G"].append("Making Software")
aut["A"].append("Making Software")
aut["ぎ"].append("Software Design総集編1990▶2000　11年分のバックナンバーを大収録")
aut["て"].append("ソフトウェアエンジニアリング論文集80’ｓデマルコ・セレクション")
aut["と"].append("ソフトウェアエンジニアリング論文集80’ｓデマルコ・セレクション")
aut["の"].append("ソフトウェアテクノロジ－４　ソフトウェアアーキテクチャ")
aut["き"].append("ソフトウェアテクノロジ－４　ソフトウェアアーキテクチャ")
aut["あ"].append("ソフトウェア開発201の鉄則")
aut["た"].append("ソフトウェア社会のゆくえ")
aut["S"].append("ソフトウェア品質知識体系ガイド第2版")
aut["I"].append("モダン・ソフトウェアエンジニアリング")
aut["H"].append("モダン・ソフトウェアエンジニアリング")
aut["P"].append("モダン・ソフトウェアエンジニアリング")
aut["P"].append("モダン・ソフトウェアエンジニアリング")
aut["M"].append("モダン・ソフトウェアエンジニアリング")
aut["よ"].append("レクチャーノート/ソフトウェア学42　ソフトウェア工学の基礎ⅩⅩⅢ")
aut["も"].append("レクチャーノート/ソフトウェア学44　ソフトウェア工学の基礎ⅩⅩⅤ")
aut["い"].append("レクチャーノート/ソフトウェア学45　ソフトウェア工学の基礎ⅩⅩⅥ")
aut["あ"].append("レクチャーノート/ソフトウェア学42　ソフトウェア工学の基礎ⅩⅩⅢ")
aut["お"].append("レクチャーノート/ソフトウェア学44　ソフトウェア工学の基礎ⅩⅩⅤ")
aut["か"].append("レクチャーノート/ソフトウェア学45　ソフトウェア工学の基礎ⅩⅩⅥ")
aut["な"].append("岩波ソフトウェア科学14　知識と推論")
aut["ど"].append("共通フレーム2013～経営者、業務部門とともに取り組む「使える」システムの実践～")
aut["M"].append("実践Vagrant")
aut["ろ"].append("実践ソフトウェアエンジニアリングーソフトウェアプロフェッショナルのための基本知識")
aut["D"].append("抽象によるソフトウェア設計　Alloyで始める形式手法")
aut["た"].append("この1冊でよくわかる　ソフトウェアテストの教科書")
aut["い"].append("この1冊でよくわかる　ソフトウェアテストの教科書")
aut["W"].append("ソフトウェアテスティングマニアックス１")
aut["W"].append("ソフトウェアテスティングマニアックス２")
aut["け"].append("テスト駆動開発入門")
aut["み"].append("EXAMPRESS情報処理教科書　プロジェクトマネージャ")
aut["み"].append("ITエンジニアのための【業務知識】がわかる本[第3版]")
aut["え"].append("WBS/EVMによるITプロジェクトマネジメント")
aut["や"].append("WBS/EVMによるITプロジェクトマネジメント")
aut["ま"].append("アジャイルな見積りと計画づくり ~価値あるソフトウェアを育てる概念と技法~")
aut["お"].append("ずっと受けたかったソフトウェア開発管理の集中研修")
aut["た"].append("ソフトウェアマネジメントモデル入門")
aut["や"].append("ソフトウェアマネジメントモデル入門")
aut["も"].append("なぜ重大な問題を見逃すのか？間違いだらけの設計レビュー")
aut["や"].append("ビジネスプロセスの教科ーアイデアを「実行力」に転換する方法")
aut["か"].append("計画の科学")
aut["R"].append("時間に遅れないプロジェクトマネジメントー制約理論の応用ー")
aut["ふ"].append("人月の神話")
aut["つ"].append("要求工学概論―要求工学の基本概念から応用まで")
aut["し"].append("要求工学概論―要求工学の基本概念から応用まで")
aut["お"].append("要求工学概論―要求工学の基本概念から応用まで")
aut["も"].append("要求工学概論―要求工学の基本概念から応用まで")
aut["ひ"].append("はじめての制御工学")
aut["さ"].append("はじめての制御工学")
aut["ひら"].append("はじめての制御工学")
aut["で"].append("金融工学入門")
aut["は"].append("情報工学入門選書７　計算機アーキテクチャ")
aut["ふ"].append("アナログ電子回路")
aut["E"].append("ストレージの原則と技術")
aut["に"].append("今度こそわかる量子コンピューター")
aut["お"].append("新世代工学シリーズ　オペレーティングシステム")
aut["M"].append("ＵＮＩＸという考え方 その設計思想と哲学")
aut["P"].append("UNIXの1/4世紀")
aut["A"].append("UNIX原典―AT&Tベル研のUNIX開発者自身によるUNIX公式解説書")
aut["と"].append("ネットワークはなぜつながるのか●知っておきたいTCP/IP、LAN、光ファイバの基礎知識●")
aut["A"].append("Computer Networks Fifth Edition")
aut["D"].append("Computer Networks Fifth Edition")
aut["も"].append("検索エンジンはなぜ見つけるのか●知っておきたいウェブ情報検索の基礎知識")
aut["み"].append("未来へつなぐデジタルシリーズ　分散システム31第二版")
aut["ま"].append("情報工学レクチャーシリーズ　分散処理システム")
aut["た"].append("ITtext 分散処理 ")
aut["つ"].append("ディペンダブルシステム―高信頼システム実現のための耐故障・検証・テスト技術")
aut["よ"].append("ディペンダブルシステム―高信頼システム実現のための耐故障・検証・テスト技術")
aut["か"].append("ディペンダブルシステム―高信頼システム実現のための耐故障・検証・テスト技術")
aut["さ"].append("ITリスク学　「情報セキュリティ」を越えて")
aut["て"].append("情報セキュリティの基礎２")
aut["と"].append("日本語入力を支える技術")
aut["す"].append("異常検知と変化検知")
aut["い"].append("異常検知と変化検知")
aut["も"].append("ITtext データマイニングの基礎")
aut["つ"].append("ITtext データマイニングの基礎")
aut["や"].append("ITtext データマイニングの基礎")
aut["ぬ"].append("ITtext データマイニングの基礎")
aut["Q"].append("バッドデータハンドブック ―データにまつわる問題への19の処方箋 ")
aut["S"].append("データサイエンス設計マニュアル")
aut["こ"].append("ことばのデータサイエンス")
aut["ぎ"].append("データサイエンティスト養成読本")
aut["T"].append("Perspectives on Data Science for Software Engineering ")
aut["L"].append("Perspectives on Data Science for Software Engineering ")
aut["T"].append("Perspectives on Data Science for Software Engineering ")
aut["み"].append("思考の世界ー曼荼羅で読み解くデータ解析の基礎")
aut["ち"].append("マルチエージェントのためのデータ解析")
aut["い"].append("岩波データサイエンス５　スパートモデリングと多変量データ解析")
aut["ふ"].append("UsefuPシリーズ２　データ分析プロセス")
aut["C"].append("The Art and Science of Analyzing Software Data")
aut["T"].append("The Art and Science of Analyzing Software Data")
aut["Th"].append("The Art and Science of Analyzing Software Data")
aut["J"].append("Beautiful Data")
aut["To"].append("Beautiful Data")
aut["な"].append("テキストマイニングを使う技術/作る技術")
aut["ろ"].append("テキストマイニングハンドブック")
aut["ひ"].append("はじめてのパターン認識")
aut["A"].append("デバッグの理論と実践")
aut["し"].append("コンピュータサイエンスで学ぶ論理回路とその設計")
aut["か"].append("情報工学入門選書6　情報と符号の理論入門")
aut["と"].append("オートマトンと形式主語")
aut["の"].append("点過程の時系列解析")
aut["お"].append("点過程の時系列解析")
aut["い"].append("岩波データサイエンス６　時系列解析ー状態空間モデル・因果解析・ビジネス応用")
aut["は"].append("画像認識")
aut["お"].append("高速文字列解析の世界――データ圧縮・全文検索・テキストマイニング")
aut["い"].append("複雑系のシミュレーション―Swarmによるマルチエージェント・システム")
aut["こ"].append("ヒューマンコンビュテーションとクラウドソーシング")
aut["ば"].append("ヒューマンコンビュテーションとクラウドソーシング")
aut["か"].append("ヒューマンコンビュテーションとクラウドソーシング")
aut["う"].append("基礎からわかる時系列分析―Rで実践するカルマンフィルタ・MCMC・粒子フィルタ― Data Science Library")
aut["ま"].append("基礎からわかる時系列分析―Rで実践するカルマンフィルタ・MCMC・粒子フィルタ― Data Science Library")
aut["は"].append("基礎からわかる時系列分析―Rで実践するカルマンフィルタ・MCMC・粒子フィルタ― Data Science Library")
aut["の"].append("カルマンフィルタ")
aut["さ"].append("モデル検査 初級編―基礎から実践まで4日で学べる ")
aut["な"].append("SPINモデル検査")
aut["ひ"].append("複素ニューラルネットワーク第2版")
aut["ご"].append("オペレーションズ・リサーチシリーズ５　意思決定のための数理モデル入門")
aut["い"].append("オペレーションズ・リサーチシリーズ５　意思決定のための数理モデル入門")
aut["い"].append("ダイアグラム別UML徹底活用第2版")
aut["G"].append("いかにして問題をとくか")
aut["よ"].append("いかにして問題を解くか　実践活用編")
aut["じ"].append("コンサルタントの道具箱")
aut["あ"].append("シカゴ大学教授法ハンドブック")
aut["で"].append("シカゴ大学教授法ハンドブック")
aut["ふ"].append("シカゴ大学教授法ハンドブック")
aut["ふれ"].append("シカゴ大学教授法ハンドブック")
aut["ふぉ"].append("シカゴ大学教授法ハンドブック")
aut["う"].append("はじめてのインストラクショナルデザイン")
aut["る"].append("はじめてのインストラクショナルデザイン")
aut["ま"].append("考える練習をしよう (子どものためのライフ・スタイル) ")
aut["ま"].append("考える練習をしよう (子どものためのライフ・スタイル) ")
aut["い"].append("授業設計マニュアル")
aut["と"].append("大学１年生からのプロジェクト学習の始め方")
aut["す"].append("授業設計マニュアル")
aut["に"].append("大学１年生からのプロジェクト学習の始め方")
aut["と"].append("脳の力を強化する思考技術　ザ・マインドマップ")
aut["の"].append("論理トレーニング１０１題")
aut["ろ"].append("デザイン思考の教科書ー欧州トップスクールが教えるイノベーションの技術ー")
aut["い"].append("デザイン思考の教科書ー欧州トップスクールが教えるイノベーションの技術ー")
aut["や"].append("デザイン思考の教科書ー欧州トップスクールが教えるイノベーションの技術ー")
aut["あ"].append("デザイン思考の教科書ー欧州トップスクールが教えるイノベーションの技術ー")
aut["さ"].append("なぜあなたの研究は進まないのか？")
aut["し"].append("やるべきことが見えてくる　研究者の仕事術　プロフェッショナル根性論")
aut["ぐ"].append("科研費　採択される3要素ーアイデア・業績・見栄え")
aut["こ"].append("科研費獲得のコツ改訂版第3版")
aut["N"].append("実験精度と誤差ー測定の確からしさとは何か")
aut["め"].append("ガイドツアー複雑系の世界ーサンタフェ研究所講義ノートから")
aut["が"].append("プレゼンテーションzen")
aut["く"].append("研究者のための国際学会プレゼンテーション")
aut["ふ"].append("「分かりやすい表現」の技術 意図を正しく伝えるための16のルール")
aut["M"].append("Designing Science Presentations: A Visual Guide to Figures, Papers, Slides, Posters, and More ")
aut["K"].append("スタディスキルズー卒研・卒論から博士論文まで、研究生活サバイバルガイド")
aut["ぽ"].append("できる研究者の論文作成メソッド")
aut["さ"].append("なぜあなたは論文が書けないのか？")
aut["ふ"].append("メール文章力の基本")
aut["こ"].append("科研費申請書の赤ペン添削ハンドブック")
aut["お"].append("改訂第6版　LATEX2ε　美文書作成入門")
aut["く"].append("改訂第6版　LATEX2ε　美文書作成入門")
aut["に"].append("原稿編集ルールブック　原稿整理のポイント")
aut["か"].append("考えすぎて書けない人のための1分間メール術")
aut["ほ"].append("新装版日本語の作文技術")
aut["あ"].append("明文術　伝わる日本語の書き方")
aut["き"].append("理科系の作文技術")
aut["な"].append("理系のための「即効！」卒業論文術")
aut["よ"].append("うまいウイスキーの科学")
aut["や"].append("うまいビールの科学")
aut["T"].append("筋トレが最強のソリューションである")
aut["Te"].append("人生の99.9％の問題は、筋トレで解決できる！")
aut["い"].append("スーパーヒューマン誕生！")
